# Generated by Django 5.2.6 on 2025-09-14 13:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Powiat',
            fields=[
                ('teryt4', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=160)),
                ('level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('probability', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('office', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='WarningCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powiat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meteo.powiat')),
                ('warning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meteo.warning')),
            ],
        ),
        migrations.AddField(
            model_name='warning',
            name='coverage',
            field=models.ManyToManyField(blank=True, related_name='warnings', through='meteo.WarningCoverage', to='meteo.powiat'),
        ),
        migrations.CreateModel(
            name='PointSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('teryt4', models.CharField(max_length=4)),
                ('area_name', models.CharField(blank=True, max_length=120)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('warnings', models.ManyToManyField(blank=True, related_name='snapshots', to='meteo.warning')),
            ],
            options={
                'indexes': [models.Index(fields=['fetched_at'], name='meteo_point_fetched_b7510b_idx'), models.Index(fields=['teryt4'], name='meteo_point_teryt4_da6837_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='warningcoverage',
            index=models.Index(fields=['warning'], name='meteo_warni_warning_36d39c_idx'),
        ),
        migrations.AddIndex(
            model_name='warningcoverage',
            index=models.Index(fields=['powiat'], name='meteo_warni_powiat__a996ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warningcoverage',
            unique_together={('warning', 'powiat')},
        ),
        migrations.AddIndex(
            model_name='warning',
            index=models.Index(fields=['valid_from', 'valid_to'], name='meteo_warni_valid_f_29c567_idx'),
        ),
    ]
