# Generated by Django 5.2.6 on 2025-09-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=128, unique=True)),
                ('teryt_powiat', models.CharField(blank=True, db_index=True, max_length=6, null=True)),
                ('teryt_woj', models.CharField(blank=True, db_index=True, max_length=2, null=True)),
                ('valid_from', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('raw', models.JSONField()),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'valid_to'], name='imgw_proxy__is_acti_5832ec_idx')],
            },
        ),
    ]
