# Generated by Django 5.2.6 on 2025-09-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerytCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('teryt4', models.CharField(blank=True, max_length=4, null=True)),
                ('area_name', models.CharField(blank=True, max_length=120)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['lat', 'lon'], name='meteo_teryt_lat_6035cb_idx')],
                'unique_together': {('lat', 'lon')},
            },
        ),
    ]
